"""empty message

Revision ID: 3b3234a623a9
Revises: e664a2f70952
Create Date: 2022-12-04 21:02:15.006000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3234a623a9'
down_revision = 'e664a2f70952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_history',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('change_log', sa.JSON(), nullable=False),
    sa.Column('workflow', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Boolean(), nullable=True),
    sa.Column('component_change', sa.Boolean(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_history_form_id'), 'form_history', ['form_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_history_form_id'), table_name='form_history')
    op.drop_table('form_history')
    # ### end Alembic commands ###
