name: Transition Jira Issue to QA

on:
  pull_request_target:
    types:
      - closed

jobs:
  transition:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: kiranka123/jira-transition-action@v2
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_TRANSITION_ID: ${{ secrets.JIRA_TRANSITION_ID }}
          PR_BODY: ${{ github.event.pull_request.body }}
